config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'payments/result'

  get 'payments/success'

  get 'payments/fail'

  get 'payments/pay'

  resources :pages , :defaults => { :format => 'json' }
  resources :images, :defaults => { :format => 'json' }
  devise_for :users, :controllers => { :registrations => 'users'}
  devise_scope :user do
    get 'users/' => 'users#index' , :defaults => { :format => 'json' }
  end

  
  get 'home/index'

  get 'prop_vals/get_sub' => 'prop_vals#get_sub',  :defaults => { :format => 'json' }
  post 'prop_vals/add_sub' => 'prop_vals#add_sub',  :defaults => { :format => 'json' }

  post 'pages/update_lang/:id' => 'pages#update_lang',  :defaults => { :format => 'json' }

  get 'api/get_filters' => 'client_api#get_filters' , :defaults => { :format => 'json' }
  get 'api/get_filters_for_new' => 'client_api#get_filters_for_new' , :defaults => { :format => 'json' }
  get 'api/get_poster/:id' => 'client_api#get_poster' , :defaults => { :format => 'json' }
  post 'api/get_by_prop' => 'adverts#get_by_prop' , :defaults => { :format => 'json' }
  get 'api/pages/:id' => 'pages#add_content', :defaults => { :format => 'json' }
  get 'api/last_poster/:count' => "client_api#last_poster" , :defaults => { :format => 'json' }
  get 'api/get_marks/' => "client_api#get_marks" , :defaults => { :format => 'json' }
  get 'api/get_pages/' => "client_api#get_pages" , :defaults => { :format => 'json' }
  get 'api/get_pages/:id' => "client_api#get_page" , :defaults => { :format => 'json' }
  get 'api/get_user/' => "client_api#get_user" , :defaults => { :format => 'json' }
  get 'api/get_user_poster/' => "client_api#get_user_poster" , :defaults => { :format => 'json' }
  get 'api/count_poster/' => "client_api#count_poster" , :defaults => { :format => 'json' }

  post 'lang/add_filter' => 'lang_values#add_filter' , :defaults => { :format => 'json' }
  get 'lang/get_filters/:id' => 'lang_values#get_filters' , :defaults => { :format => 'json' }

  get 'users/' => 'users#index' , :defaults => { :format => 'json' }

  get 'control' => 'control#index'
  get 'control/private_person'
  get 'control/dealer'
  get 'control/admin'

  get 'poster/set_top/:id' => 'adverts#set_top',  :defaults => { :format => 'json' }

  post 'service/add/:id' => 'services#add',  :defaults => { :format => 'json' }

  resources :adverts, path: "/posters",  :defaults => { :format => 'json' }
  resources :prop_vals,  :defaults => { :format => 'json' }
  resources :properties, :defaults => { :format => 'json' }
  resources :groups,  :defaults => { :format => 'json' }
  resources :lang_values,  :defaults => { :format => 'json' }
  resources :langs,  :defaults => { :format => 'json' }
  resources :services,  :defaults => { :format => 'json' }

  get 'add_filter' => 'groups#add_filter' , :defaults => { :format => 'json' }
  get 'remove_filter' => 'groups#remove_filter' , :defaults => { :format => 'json' }
  root 'home#index'

  get '*path' => 'home#index'

end

app/models/service.rb
class Service < ActiveRecord::Base

  has_many :service_users
  has_many :users, through: :service_users

  has_many :service_adverts
  has_many :adverts, through: :service_adverts
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :add]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @my_service = current_user.services
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add

    @service_user =ServiceUser.create
    @service_user.service = @service
    @service_user.user = current_user
    @service_user.save

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :price, :duration, :s_type, :desc, :currency, :count)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :s_type %><br>
    <%= f.number_field :s_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Duration</th>
      <th>S type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.price %></td>
        <td><%= service.duration %></td>
        <td><%= service.s_type %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @service.duration %>
</p>

<p>
  <strong>S type:</strong>
  <%= @service.s_type %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>