config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'payments/result'

  get 'payments/success'

  get 'payments/fail'

  get 'payments/pay'

  resources :pages , :defaults => { :format => 'json' }
  resources :images, :defaults => { :format => 'json' }
  devise_for :users, :controllers => { :registrations => 'users'}
  devise_scope :user do
    get 'users/' => 'users#index' , :defaults => { :format => 'json' }
  end

  
  get 'home/index'

  get 'prop_vals/get_sub' => 'prop_vals#get_sub',  :defaults => { :format => 'json' }
  post 'prop_vals/add_sub' => 'prop_vals#add_sub',  :defaults => { :format => 'json' }

  post 'pages/update_lang/:id' => 'pages#update_lang',  :defaults => { :format => 'json' }

  get 'api/get_filters' => 'client_api#get_filters' , :defaults => { :format => 'json' }
  get 'api/get_filters_for_new' => 'client_api#get_filters_for_new' , :defaults => { :format => 'json' }
  get 'api/get_poster/:id' => 'client_api#get_poster' , :defaults => { :format => 'json' }
  post 'api/get_by_prop' => 'adverts#get_by_prop' , :defaults => { :format => 'json' }
  get 'api/pages/:id' => 'pages#add_content', :defaults => { :format => 'json' }
  get 'api/last_poster/:count' => "client_api#last_poster" , :defaults => { :format => 'json' }
  get 'api/get_marks/' => "client_api#get_marks" , :defaults => { :format => 'json' }
  get 'api/get_pages/' => "client_api#get_pages" , :defaults => { :format => 'json' }
  get 'api/get_pages/:id' => "client_api#get_page" , :defaults => { :format => 'json' }
  get 'api/get_user/' => "client_api#get_user" , :defaults => { :format => 'json' }
  get 'api/get_user_poster/' => "client_api#get_user_poster" , :defaults => { :format => 'json' }
  get 'api/count_poster/' => "client_api#count_poster" , :defaults => { :format => 'json' }

  post 'lang/add_filter' => 'lang_values#add_filter' , :defaults => { :format => 'json' }
  get 'lang/get_filters/:id' => 'lang_values#get_filters' , :defaults => { :format => 'json' }

  get 'users/' => 'users#index' , :defaults => { :format => 'json' }

  get 'control' => 'control#index'
  get 'control/private_person'
  get 'control/dealer'
  get 'control/admin'

  get 'poster/set_top/:id' => 'adverts#set_top',  :defaults => { :format => 'json' }

  post 'service/add/:id' => 'services#add',  :defaults => { :format => 'json' }

  resources :adverts, path: "/posters",  :defaults => { :format => 'json' }
  resources :prop_vals,  :defaults => { :format => 'json' }
  resources :properties, :defaults => { :format => 'json' }
  resources :groups,  :defaults => { :format => 'json' }
  resources :lang_values,  :defaults => { :format => 'json' }
  resources :langs,  :defaults => { :format => 'json' }
  resources :services,  :defaults => { :format => 'json' }

  get 'add_filter' => 'groups#add_filter' , :defaults => { :format => 'json' }
  get 'remove_filter' => 'groups#remove_filter' , :defaults => { :format => 'json' }
  root 'home#index'

  get '*path' => 'home#index'

end

app/models/lang.rb
class Lang < ActiveRecord::Base
  has_many :lang_values

  has_many :pages
  has_many :page_lang_rels, :through => :pages
end

app/controllers/langs_controller.rb
class LangsController < ApplicationController
  before_action :set_lang, only: [:show, :edit, :update, :destroy]

  # GET /langs
  # GET /langs.json
  def index
    @langs = Lang.all
  end

  # GET /langs/1
  # GET /langs/1.json
  def show
  end

  # GET /langs/new
  def new
    @lang = Lang.new
  end

  # GET /langs/1/edit
  def edit
  end

  # POST /langs
  # POST /langs.json
  def create
    @lang = Lang.new(lang_params)

    respond_to do |format|
      if @lang.save
        format.html { redirect_to @lang, notice: 'Lang was successfully created.' }
        format.json { render :show, status: :created, location: @lang }
      else
        format.html { render :new }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langs/1
  # PATCH/PUT /langs/1.json
  def update
    respond_to do |format|
      if @lang.update(lang_params)
        format.html { redirect_to @lang, notice: 'Lang was successfully updated.' }
        format.json { render :show, status: :ok, location: @lang }
      else
        format.html { render :edit }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langs/1
  # DELETE /langs/1.json
  def destroy
    @lang.destroy
    respond_to do |format|
      format.html { redirect_to langs_url, notice: 'Lang was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lang
      @lang = Lang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lang_params
      params.require(:lang).permit(:short_name, :long_name)
    end
end

app/helpers/langs_helper.rb
module LangsHelper
end

app/views/langs/_form.html.erb
<%= form_for(@lang) do |f| %>
  <% if @lang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lang.errors.count, "error") %> prohibited this lang from being saved:</h2>

      <ul>
      <% @lang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :long_name %><br>
    <%= f.text_field :long_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/langs/edit.html.erb
<h1>Editing Lang</h1>

<%= render 'form' %>

<%= link_to 'Show', @lang %> |
<%= link_to 'Back', langs_path %>

app/views/langs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Langs</h1>

<table>
  <thead>
    <tr>
      <th>Short name</th>
      <th>Long name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @langs.each do |lang| %>
      <tr>
        <td><%= lang.short_name %></td>
        <td><%= lang.long_name %></td>
        <td><%= link_to 'Show', lang %></td>
        <td><%= link_to 'Edit', edit_lang_path(lang) %></td>
        <td><%= link_to 'Destroy', lang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lang', new_lang_path %>

app/views/langs/new.html.erb
<h1>New Lang</h1>

<%= render 'form' %>

<%= link_to 'Back', langs_path %>

app/views/langs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short name:</strong>
  <%= @lang.short_name %>
</p>

<p>
  <strong>Long name:</strong>
  <%= @lang.long_name %>
</p>

<%= link_to 'Edit', edit_lang_path(@lang) %> |
<%= link_to 'Back', langs_path %>